### ISSUE TITLE
Error when trying to run server.

### ISSUE THREAD

**Issue by AceBeaker2** [AmericanPresidentJimmyCarter/yasd-discord-bot#1]
For some reason the server just won't start. I don't know why, and this is the third time ive tried it(running linux mint 21)
Im really hoping you understand these logs better than I do.

Logs:
[logs.txt](https://github.com/AmericanPresidentJimmyCarter/yasd-discord-bot/files/9427846/logs.txt)

**Comment by AmericanPresidentJimmyCarter** [comment]
It looks like the other image generation methods were not disabled and you're missing stuff for them. Did you run this?

```py
python flow_parser.py --enable-stable-diffusion --disable-dalle-mega --disable-glid3xl
jina flow --uses flow.tmp.yml
```

**Comment by AceBeaker2** [comment]
No, Thank You!!!

**Comment by AceBeaker2** [comment]
So sorry, it seems to be working perfectly now. Im still not using the docker image because im having a few problems (nvidia docker doesn't like linux mint that much), but its all perfect! Thank you for making this tool.

**Comment by AmericanPresidentJimmyCarter** [comment]
No problem! Glad it's working.
