### ISSUE TITLE
interpolate throws a DocumentArray error

### ISSUE THREAD

**Issue by murmur9283** [AmericanPresidentJimmyCarter/yasd-discord-bot#10]
I tried to run
/interpolate and filled out the two prompts

and got
Now beginning work on "interpolate "cat sitting on a sofa" to dog sitting on a sofa" for murmur5786. Please be patient until I finish that.
Got unknown error on interpolate "cat sitting on a sofa" to dog sitting on a sofa: <DocumentArray (length=0) at 140684863006336> is empty

**Comment by AmericanPresidentJimmyCarter** [comment]
Did you update to the latest dalle-jina? It works here locally.

![Screenshot_2022-08-31_08-44-13](https://user-images.githubusercontent.com/110263573/187681339-9f27b506-d513-4fbb-bfe4-c5a0a462d805.png)

**Comment by murmur9283** [comment]
Thank you for coming back. I had a pretty fresh install (3 days ago) but will try to re-install in that case and update here

**Comment by AmericanPresidentJimmyCarter** [comment]
The other problem might be that you're using the low VRAM version and I just haven't coded the interpolate function for that yet. I hope to be able to later this week.

**Comment by AceBeaker2** [comment]
Yep, Im using the low VRAM version and getting the same error

**Comment by AmericanPresidentJimmyCarter** [comment]
OK, worry not, this will be implemented for that branch soon.

**Comment by AmericanPresidentJimmyCarter** [comment]
The `optimized-sd` branch has been updated. To update, you'll have to destroy the old branch as there was a rebase and force push. Follow these commands:

```bash
cd dalle/dalle-flow
git checkout main
git fetch --all --prune
git branch -D optimized-sd
git checkout optimized-sd
```

This should make the interpolate command available to you. Please let me know how it goes.

**Comment by AmericanPresidentJimmyCarter** [comment]
@AceBeaker2 Just let me know if everything is fixed on your end and I will close the issue.

**Comment by AmericanPresidentJimmyCarter** [comment]
Haven't heard anything back, presuming it's been fixed.
