### ISSUE TITLE
Riff buttons should not be deactivated

### ISSUE THREAD

**Issue by murmur9283** [AmericanPresidentJimmyCarter/yasd-discord-bot#11]
Love the new buttons - just a minor improvement. When a riff-button is pressed it is deactivated. This is fine for upscaling but if I want to do another riff of the same image I have to fall back to the traditional copy-pasting.

Thank you for your work - huge improvement!!

**Comment by AmericanPresidentJimmyCarter** [comment]
Sure, I can change that.

**Comment by AmericanPresidentJimmyCarter** [comment]
Closed in https://github.com/AmericanPresidentJimmyCarter/yasd-discord-bot/commit/e55081b14c59982ea7799af5798a32c38383a394
