### ISSUE TITLE
Buttons becoming defunct after a while

### ISSUE THREAD

**Issue by murmur9283** [AmericanPresidentJimmyCarter/yasd-discord-bot#14]
Both, Riff and upscale-buttons throw an error after a couple of minutes when pressed. 

![image](https://user-images.githubusercontent.com/64155531/187857118-d784a144-f17a-47b6-a926-d2d08cdbf50a.png)

**Comment by murmur9283** [comment]
might be resolved in latest build. I wait a bit and re-test old buttons

**Comment by murmur9283** [comment]
Can confirm it is still an issue with newest build. Buttons are defunct after about 10mins

**Comment by AmericanPresidentJimmyCarter** [comment]
Button action breaks between closing and reopening the bot too. I am not sure how Discord works with timing this stuff out, I will look into it. In the meantime you can use the IDs to riff/upscale older images.

**Comment by AmericanPresidentJimmyCarter** [comment]
It seems I need to make the views (things the buttons live) persistent. I can do this with the `add_view` function. I will look into this later today.

https://github.com/Rapptz/discord.py/blob/33c9708c2dfd9c08380c50fe29c8e5a3dea072e9/discord/client.py#L1940-L1972
