### ISSUE TITLE
Print commands after using slash commands

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [AmericanPresidentJimmyCarter/yasd-discord-bot#16]
It would be good to print the legacy commands after using slash commands so that people might easily copy paste the commands of others.

**Comment by aaronsantiago** [comment]
Currently riffs/upscales don't show information about the prompt, I think they should.

I really want this--can you point me into the direction of how to implement something like this? I want ways to save metadata images and right now getting the relevant info (prompt, original author) etc. is a little opaque. They only seem to get the run ID. The way I'd approach this naively is to add the runs to a dictionary, but those would get unloaded if the bot restarts. I feel like the prompt is saved somewhere..

**Comment by AmericanPresidentJimmyCarter** [comment]
Technically all the runs from the start of the bot are stored in the `temp_json` folder as requests. They will get overwritten when the bot restarts and users make new requests.

I am going to attempt to implement serialization of commands tonight. People on the LAION server have requested pings with links to their original post when a call is completed, I will serialize the commands as `>` commands there, since those are more readily copy-pastable into discord to rerun the command. Slash commands are pretty frustrating to copy-paste by comparison, at least for me.

**Comment by AmericanPresidentJimmyCarter** [comment]
The prompts by the way are stored in the jina `Document`s as `.text`.

**Comment by AmericanPresidentJimmyCarter** [comment]
Closed by c85d7c4a31cc88c404189364f3c1fd6d504e6bbd.

@aaronsantiago Looks like this 

![Screenshot_2022-09-12_19-55-31](https://user-images.githubusercontent.com/110263573/189778984-5018579c-0cd5-4011-be75-c0bd34a21cb6.png)

For better monitoring of commands you might want to use Prometheus and Grafana with dalle-flow: https://docs.jina.ai/how-to/monitoring/

If you still want indexing of some kinda we could probably use SQLite3, but please open a different issue for that.
