### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by ThrownLemon** [AmericanPresidentJimmyCarter/yasd-discord-bot#2]
Getting an error after issuing **>help** command in discord, any ideas?

`discord.ext.commands.context.Context object at 0x7f68d61344f0> Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'`

**Comment by AmericanPresidentJimmyCarter** [comment]
That's strange, the `help` command is unset so it should just default to the regular help. I just tried `>help` in my server and got this.

```
This is a Helper Bot

​No Category:
  help        Shows this message
  image       
  image2image 
  riff        
  upscale     

Type >help command for more info on a command.
You can also type >help category for more info on a category.
```

If you didn't already, be sure to set the bot to have message and message content permissions.

![Screenshot_2022-08-26_08-53-20](https://user-images.githubusercontent.com/110263573/186907979-5ac728e5-b0aa-48da-8534-cbf3cce339fc.png)

In the server itself, ensure that the bot user has the ability to send/receive messages.

**Comment by ThrownLemon** [comment]
Yeah all the permissions are correct on the bot and the server.

The weird thing is it works on my personal discord server just not on this another server, so there must be some conflicting permissions somewhere.

**Comment by AmericanPresidentJimmyCarter** [comment]
That is very strange, I have no idea. If you figure it out later let me know.

**Comment by ThrownLemon** [comment]
no longer an issue latest version
