### ISSUE TITLE
[Feature Request] Add commands to a queue instead of rejecting them

### ISSUE THREAD

**Issue by aaronsantiago** [AmericanPresidentJimmyCarter/yasd-discord-bot#22]
Title. It makes it difficult to manage generations as the bot has to be babysat to try out multiple ideas

**Comment by AmericanPresidentJimmyCarter** [comment]
Commands are already auto-queued if you remove the global `currently_fetching_ai_image` dict and the checks around it. I can make it a command line option, it's mostly there to prevent people from abusing the bot with hundreds of simultaneous requests. I could replace it with the current number of simultaneous requests and bounce them when they hit a certain number of requests too.

**Comment by aaronsantiago** [comment]
A command line option makes sense to me. For me, my discord bot is only accessed by trusted users and the queue would be extremely useful for our use.
