### ISSUE TITLE
[Feature Request] Be able to lower the default amount of steps.

### ISSUE THREAD

**Issue by AceBeaker2** [AmericanPresidentJimmyCarter/yasd-discord-bot#25]
The title

**Comment by bdonnell** [comment]
I would be very happy with a steps argument, though I want to increase steps (for correlated increased strengths.)  The readme shows a steps field in the / command of the demo screenshot, but as far as I can tell it doesn't actually exist.

**Comment by AmericanPresidentJimmyCarter** [comment]
There is a default steps argument, `--default-steps`. You can change the steps for the `/image`/`>image` command. Steps for image2image or riff are controlled by the strength, out of 50, but you can "multiply" the number of image2image/riff calls with "iterations".

![Screenshot_2022-09-11_09-49-06](https://user-images.githubusercontent.com/110263573/189531086-5d9f87b3-52cf-4507-9f31-0de245f44854.png)

**Comment by aaronsantiago** [comment]
Can you elaborate on the relationship between strength and steps for img2img and riff? Usually strength means how much noise is added to the image for each step, and steps are a separate parameter.

**Comment by AmericanPresidentJimmyCarter** [comment]
Sure, `t_enc = int(strength * steps)` so if you have `dalle-flow` set to 50 steps globally, the number of steps performed `t_enc` is equal to `int(strength * steps)`. e.g. strength=0.75, global steps=50, then `t_enc` is 37, or 37 steps will be performed.

**Comment by aaronsantiago** [comment]
Does strength not have any bearing on the amount of noise added to the image during img2img? am i misunderstanding how that system works?

**Comment by AmericanPresidentJimmyCarter** [comment]
It does. Noising is applied to according to the sigma schedule, for k samplers that's `noise = torch.randn_like(x0) * sigmas[steps - t_enc - 1]`. Less noise is applied for fewer steps.

**Comment by AmericanPresidentJimmyCarter** [comment]
And fwiw steps could be added as an option in the future in `dalle-flow` -- just too much other stuff to work on right now and the default steps (50) works pretty well.

**Comment by AceBeaker2** [comment]
@AmericanPresidentJimmyCarter

**Comment by AmericanPresidentJimmyCarter** [comment]
When running `python bot.py` eg `python bot.py TOKEN --default-steps 25`
