### ISSUE TITLE
Option to select the number of images being output

### ISSUE THREAD

**Issue by ThrownLemon** [AmericanPresidentJimmyCarter/yasd-discord-bot#3]
Not sure if this is already an option or if it's possible to make it configurable?

For example something like below?

-  >image foo bar (samples=2) 
- >image foo bar (images=4)

**Comment by ThrownLemon** [comment]
nevermind i found the upscale command :P

**Comment by AmericanPresidentJimmyCarter** [comment]
Right now it is fixed, I can add an option later but found for the most part I didn't need it. To get 9 images while scanning through seeds, use `(seed_search=t)`.
