### ISSUE TITLE
[Feature Request] Implement Textual Inversion with img2img

### ISSUE THREAD

**Issue by AceBeaker2** [AmericanPresidentJimmyCarter/yasd-discord-bot#34]
https://www.youtube.com/watch?v=WsDykBTjo20
https://github.com/hlky/sd-enable-textual-inversion

Create more advanced images from other images with textual inversion

**Comment by AmericanPresidentJimmyCarter** [comment]
Already a dalle-flow issue

https://github.com/jina-ai/dalle-flow/issues/111
