### ISSUE TITLE
Store additional metadata in Jina DocArray tags

### ISSUE THREAD

**Issue by aaronsantiago** [AmericanPresidentJimmyCarter/yasd-discord-bot#37]
Title. 
Some good tags to have:
- Which user requested the image
- Which channel the request was made in
- Which guild the request was made in
- ID of the original if it is a riff or an upscale

**Comment by AmericanPresidentJimmyCarter** [comment]
The easiest things to store from the current architecture of the software are the user ID and the original ID. If you need the guild and channel that could be added, but I can more easily do the other two if that suffices. The develop branch also has a lot of other information related to the request now stored in the docarray document.

**Comment by aaronsantiago** [comment]
Guild and channel aren't nearly as important to me as user ID and original ID. Looking thru what's on develop it includes the API and other parameters for the run which is great!
