### ISSUE TITLE
Riff and interpolate not working

### ISSUE THREAD

**Issue by Goolashe** [AmericanPresidentJimmyCarter/yasd-discord-bot#57]
When attempting to riff an image, it gives an identical error as seen in issue #10. When trying to interpolate, I get the error "list index out of range".

They might be related to the following error I get in the logs:

> /usr/local/lib/python3.10/dist-packages/docarray/proto/io/ndarray.py:149: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:178.)
> 
>   return from_numpy(x)

I've been digging around as to the cause for this without much luck so far. [Here](https://github.com/Goolashe/yasd-discord-bot-docker/blob/master/Dockerfile) is the Dockerfile I build the image with. It currently uses the nvidia/cuda:11.8.0-runtime-ubuntu22.04 image to build off of, but I would also have this issue with just ubuntu:22.04 as well.

**Comment by AmericanPresidentJimmyCarter** [comment]
That's a Jina DocArray related issue and should have no bearing on the software.

Does `>prompt` and the rest of the commands work correctly? For persistence you're going to want to also mount the following folders as virtual volumes: `image_docarrays` and `temp_json`. Or alternatively just git clone this repo and mount the whole folder as the virtual volume inside the docker, replacing the copy step.

**Comment by Goolashe** [comment]
Ah, dang, alright. Guess I'll have to dig into that and/or wait for an update.

And yeah, all other commands are working just fine. Thank you for the additional input as well on the virtual volumes!
