### ISSUE TITLE
Repos do not exist

### ISSUE THREAD

**Issue by AceBeaker2** [AmericanPresidentJimmyCarter/yasd-discord-bot#6]
git clone https://github.com/CompVis/latent-diffusio324n.git
git clone https://github.com/StableDiffusion/latent-diffusion.git

both do not exist

**Comment by AceBeaker2** [comment]
Ive been swapping them out for

git clone https://github.com/CompVis/stable-diffusion
git clone https://github.com/CompVis/latent-diffusion

**Comment by AmericanPresidentJimmyCarter** [comment]
Yeah, those are the right ones
