### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ionutanton** [AmericanPresidentJimmyCarter/yasd-discord-bot#8]
A quality of live improvement for the bot would be implementing buttons such as MJ has for redoing the prompt or upscaling each of the 4 images.
a good reference for buttons using discord.py seems to be https://gist.github.com/lykn/bac99b06d45ff8eed34c2220d86b6bf4.
another improvement would be that the message "Now beginning work on..." could be edited with the final result.

very nice work on the bot.

**Comment by AmericanPresidentJimmyCarter** [comment]
Thanks, I will look into this. This appears to be a new feature for the bot UI.

**Comment by AmericanPresidentJimmyCarter** [comment]
Closed by https://github.com/AmericanPresidentJimmyCarter/yasd-discord-bot/commit/00fe1d6ededf5b78b29aa44c8b228fca78cb0de7
