### ISSUE TITLE
bot will not start

### ISSUE THREAD

**Issue by ionutanton** [AmericanPresidentJimmyCarter/yasd-discord-bot#9]
i get an error at start. below the error.
Traceback (most recent call last):
  File "bot.py", line 26, in <module>
    currently_fetching_ai_image: dict[str, Union[str, bool]] = {}
TypeError: 'type' object is not subscriptable
running on windows. python 3.8

**Comment by AmericanPresidentJimmyCarter** [comment]
I think it uses typing not available on 3.8, but should work on 3.9+. It was developed on 3.10. Are you able to update? I am not sure that some of the advanced Discord types will work on 3.8 either.
